# Generated by Django 6.0.6 on 2026-06-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('optimal_soil_type', models.CharField(default='Red-Brown Earth', max_length=100)),
                ('base_water_multiplier', models.FloatField(help_text='Multiplier for standard irrigation calculation')),
                ('min_temp', models.FloatField(help_text='Minimum viable temperature in Celsius')),
                ('max_temp', models.FloatField(help_text='Maximum viable temperature in Celsius')),
            ],
        ),
    ]
