# Generated by Django 6.0.6 on 2026-06-28 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.FloatField()),
                ('humidity_percent', models.FloatField()),
                ('rainfall_mm', models.FloatField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical - Take Action Now')], max_length=10)),
                ('risk_score', models.FloatField(help_text='0-100 risk score')),
                ('alert_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pathogen', models.CharField(max_length=100)),
                ('min_temperature_c', models.FloatField(help_text='Minimum temperature for disease development')),
                ('max_temperature_c', models.FloatField(help_text='Maximum temperature for disease development')),
                ('min_humidity_percent', models.FloatField(help_text='Minimum humidity % that favors disease')),
                ('max_yield_loss_percent', models.FloatField(help_text='Maximum yield loss if untreated')),
                ('symptoms', models.TextField(help_text='Visible symptoms to look for')),
                ('prevention', models.TextField(help_text='Recommended prevention/action')),
                ('research_source', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='LocalCrop',
        ),
        migrations.AddField(
            model_name='diseasealert',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.diseaseprofile'),
        ),
    ]
