# Generated by Django 6.0.6 on 2026-07-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_diseasealert_diseaseprofile_delete_localcrop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasealert',
            name='farmer',
        ),
        migrations.AddField(
            model_name='diseasealert',
            name='farmer_uid',
            field=models.CharField(db_index=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
