# Generated by Django 6.0.6 on 2026-06-24 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropWaterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, unique=True)),
                ('daily_water_requirement_mm', models.FloatField(help_text='Average daily water requirement in millimeters')),
                ('optimal_soil_moisture_percent', models.FloatField(help_text='Ideal soil moisture percentage for this crop')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.FloatField()),
                ('humidity_percent', models.FloatField()),
                ('rainfall_mm', models.FloatField(default=0)),
                ('moisture_deficit_mm', models.FloatField()),
                ('should_irrigate', models.BooleanField()),
                ('recommended_volume_liters', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irrigation.cropwaterprofile')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
