# Generated by Django 6.0.6 on 2026-06-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationrecommendation',
            name='recommendation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cropwaterprofile',
            name='daily_water_requirement_mm',
            field=models.FloatField(help_text='Average daily water requirement in millimeters (FCRDI, 1999)'),
        ),
    ]
