# Generated by Django 6.0.6 on 2026-07-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0002_irrigationrecommendation_recommendation_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationrecommendation',
            name='farmer',
        ),
        migrations.AddField(
            model_name='irrigationrecommendation',
            name='farmer_uid',
            field=models.CharField(db_index=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
