# Generated by Django 6.0.6 on 2026-07-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(default='Big Onion', max_length=100)),
                ('region', models.CharField(default='Dambulla', max_length=100)),
                ('average_yield_mt_per_ha', models.FloatField(default=20.4)),
                ('best_irrigation_method', models.CharField(default='Agri Well + Irrigation System', max_length=200)),
                ('best_irrigation_yield', models.FloatField(default=20.73)),
                ('best_land_type', models.CharField(default='Paddy land', max_length=100)),
                ('best_land_type_yield', models.FloatField(default=19.31)),
                ('best_seed_variety', models.CharField(default='Local & Import mix', max_length=100)),
                ('best_seed_variety_yield', models.FloatField(default=20.47)),
                ('harvest_start_month', models.CharField(default='September', max_length=20)),
                ('harvest_end_month', models.CharField(default='October', max_length=20)),
                ('production_cost_per_kg', models.FloatField(default=39.45)),
                ('data_source', models.CharField(default='DCS Big Onion Survey 2021 (Yala Season)', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crop Advisory',
                'verbose_name_plural': 'Crop Advisories',
                'unique_together': {('crop_name', 'region')},
            },
        ),
    ]
